---
# This is a demo of how the group command works.

- hosts: all
  user: root
  sudo: yes

  tasks:

    # Walk through group creation, modification, and deletion
    - name: create a group
      action: group name=tset

    # You can only modify the group's gid
    - action: group name=tset gid=7777

    # And finally remove the group
    - action: group name=tset state=absent
