
Vagrant.configure("2") do |config|

  config.vm.box = "centos64_x64"
  ##  config.vm.base_mac =  "08002710AB51"
  #  config.vm.box_url = "http://vntx-box.s3.amazonaws.com/centos6.box"
  #  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20130427.box"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"
  config.vm.network :forwarded_port, guest: 80, host: 9090
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
  #   # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file base.pp in the manifests_path directory.
  #

  # first, get puppet on there
  config.vm.provision :shell, :path => "centos6_puppet.sh"
  # second, get openvp on there 
  config.vm.provision :shell, :path => "centos6_openvpn.sh"

########  http://safesrv.net/install-openvpn-on-centos/
# c.vm.provision :shell, :inline => 'yum install -y wget'
# c.vm.provision :shell, :inline => 'wget https://github.com/downloads/OpenVPN/easy-rsa/easy-rsa-2.2.0_master.tar.gz -P/vagrant '
# c.vm.provision :shell, :inline => 'tar -zxvf /vagrant/easy-rsa-2.2.0_master.tar.gz'
  config.vm.provision :shell, :inline => 'if [ ! -d /usr/share/doc/openvpn-2.2.2 ]; then mkdir /usr/share/doc/openvpn-2.2.2; fi'
  config.vm.provision :shell, :inline => 'if [ ! -d /usr/share/openvpn ]; then mkdir /usr/share/openvpn; fi'
  config.vm.provision :shell, :inline => 'cp -R /vagrant/easy-rsa-2.2.0_master/easy-rsa/ /usr/share/doc/openvpn-2.2.2/easy-rsa/'
  config.vm.provision :shell, :inline => 'cp -R /vagrant/easy-rsa-2.2.0_master/easy-rsa/ /usr/share/openvpn/easy-rsa/'
# c.vm.provision :shell, :inline => 'if [ ! -f rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm ]; then wget -q http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm; fi'
# c.vm.provision :shell, :inline => 'yum install -y rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm || exit 0'
################################

  # then hand over to puppet to do the rest
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "bootstrap.pp"
    puppet.module_path    = "puppet/modules"
    puppet.options        = "--hiera_config /vagrant/hiera.yaml --debug"
#    puppet.options        = "--hiera_config /vagrant/hiera.yaml --verbose "
  end
end

